### ISSUE TITLE
`Class "Kirby" not found` in composer setup

### ISSUE THREAD

**Issue by lukasleitsch** [eXpl0it3r/kirby-uniform-recaptcha#3] opened 2021-05-17 08:39 UTC
After installing Kirby, the uniform plugin and your plugin in a fresh installation, the error `Fatal error: Uncaught Error: Class "Kirby" not found in vendor/mzur/kirby-uniform/config.php:3` occurs.

## Steps to reproduce

1. composer create-project getkirby/starterkit your-project
2. composer require mzur/kirby-uniform:^4.0
3. composer require expl0it3r/kirby-uniform-recaptcha
4. Open den home page

After installation another Kirby plugin. (`composer require getkirby/geo`) the error disappear. I seem to be an ordering issue during loading the classes and den `Kirby` Alias.

**Comment by eXpl0it3r** [comment] 2021-05-18 10:06
Looks like the error actually originates from kirby-uniform, but I wouldn't be surprised if it was caused by my plugin.

```
Fatal error: Uncaught Error: Class 'Kirby' not found in D:\Private\Dev\Web\kirby\vendor\mzur\kirby-uniform\config.php:3 Stack trace:
#0 D:\Private\Dev\Web\kirby\vendor\composer\autoload_real.php(71): require()
#1 D:\Private\Dev\Web\kirby\vendor\composer\autoload_real.php(61): composerRequire412880b8074d32c15b15635baf85cfa4('513c89d6408d266...', 'D:\\Private\\Dev\\...')
#2 D:\Private\Dev\Web\kirby\vendor\autoload.php(7): ComposerAutoloaderInit412880b8074d32c15b15635baf85cfa4::getLoader()
#3 D:\Private\Dev\Web\kirby\kirby\bootstrap.php(21): include('D:\\Private\\Dev\\...')
#4 D:\Private\Dev\Web\kirby\index.php(3): require('D:\\Private\\Dev\\...')
#5 {main} thrown in D:\Private\Dev\Web\kirby\vendor\mzur\kirby-uniform\config.php on line 3
```

I'm really not an expert on autoload and composer setup, so maybe @mzur has some inputs for me?

**Comment by lukasleitsch** [comment] 2021-05-18 12:06
I guess it's a composer autoload issue. Here is what I found out.

The Uniform plugins loads a `config.php` with the composer autoloader. https://github.com/mzur/kirby-uniform/blob/bfd1464c8e135b06200ed928f6bf571df3578310/composer.json#L31

After installing the uniform plugin in a fresh installation of kirby the `kirby/config/setup.php` file will be loaded before the uniform config. (The alias for the Kirby Class will be setup in `/kirby/config/setup.php`)

``` php
// vendor/composer/autoload_files.php
return array(
    '7e9bd612cc444b3eed788ebbe46263a0' => $vendorDir . '/laminas/laminas-zendframework-bridge/src/autoload.php',
    'e862d9fce5eaa28c798b151ac7fc8bc6' => $vendorDir . '/mzur/kirby-flash/src/helpers.php',
    '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => $vendorDir . '/symfony/polyfill-mbstring/bootstrap.php',
    '04c6c5c2f7095ccf6c481d3e53e1776f' => $vendorDir . '/mustangostang/spyc/Spyc.php',
    '316f57472eecfe71b6733d9d2acbcae9' => $vendorDir . '/mzur/kirby-form/src/helpers.php',
    'f864ae44e8154e5ff6f4eec32f46d37f' => $baseDir . '/kirby/config/setup.php',
    '87988fc7b1c1f093da22a1a3de972f3a' => $baseDir . '/kirby/config/helpers.php',
    '1f7ddc2baab73fdd75a4663f7a275bb1' => $vendorDir . '/mzur/kirby-uniform/src/helpers.php',
);
```

Now I installed your plugin. The order of the composer autoloading changed:

```php
return array(
    'e862d9fce5eaa28c798b151ac7fc8bc6' => $vendorDir . '/mzur/kirby-flash/src/helpers.php',
    '7e9bd612cc444b3eed788ebbe46263a0' => $vendorDir . '/laminas/laminas-zendframework-bridge/src/autoload.php',
    '316f57472eecfe71b6733d9d2acbcae9' => $vendorDir . '/mzur/kirby-form/src/helpers.php',
    '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => $vendorDir . '/symfony/polyfill-mbstring/bootstrap.php',
    '04c6c5c2f7095ccf6c481d3e53e1776f' => $vendorDir . '/mustangostang/spyc/Spyc.php',
    '513c89d6408d266be7db63374b5a5cc9' => $vendorDir . '/mzur/kirby-uniform/config.php',
    '1f7ddc2baab73fdd75a4663f7a275bb1' => $vendorDir . '/mzur/kirby-uniform/src/helpers.php',
    'f864ae44e8154e5ff6f4eec32f46d37f' => $baseDir . '/kirby/config/setup.php',
    '87988fc7b1c1f093da22a1a3de972f3a' => $baseDir . '/kirby/config/helpers.php',
);
```

The config file of uniform will be loaded before the Kirby Class Alias is set up.

Maybe this could the reason for this issue.

**Comment by eXpl0it3r** [comment] 2021-05-18 12:36
Yeah that makes sense, I just don't know how the load order is influenced and why installing my plugin, changes the loading order of other plugins. Maybe I need an additional file or some more lines in my autoloader script.

**Comment by lukasleitsch** [comment] 2021-05-19 12:05
I think I found a solution for this issue: PR is created: https://github.com/mzur/kirby-uniform/pull/204

**Comment by eXpl0it3r** [comment] 2021-05-20 11:51
With the fix applied, things seem to work fine again, as such I'll close this issue.

```
composer create-project getkirby/starterkit kirby
cd kirby
composer require mzur/kirby-uniform
composer require expl0it3r/kirby-uniform-recaptcha
```

**Closed as completed by eXpl0it3r** 2021-05-20 11:51 UTC
Labels: bug
